---
- name: disable ipv6
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
    validate: grep -ir 'net.ipv6.conf.default.disable_ipv6 = 1' %s
    create: yes
  tags:
    - ubuntu

- name: Install qbittorrent
  package:
    name: qbittorrent
    state: present
  tags:
    - ubuntu

- name: Install qbittorrent-nox
  package:
    name: qbittorrent-nox
    state: present
  tags:
    - ubuntu
