- name: Remove All jetbrains apps
  file:
    state: absent
    path: "/home/{{ username }}/{{ item.jetbrains }}"
  loop:
    - { jetbrains: .IntelliJIdea2019.* }
    - { jetbrains: .PyCharm2019.* }
    - { jetbrains: .CLion2019.* }
    - { jetbrains: .DataGrip2019.* }
    - { jetbrains: .GoLand2019.* }
    - { jetbrains: .RubyMine2019.* }
    - { jetbrains: .WebStorm2019.* }
    - { jetbrains: .java }

- name: Remove .java
  file:
    state: absent
    path: "/home/{{ username }}/.java"

- name: Install pycharm and intellij
  snap:
    name:
      - pycharm-professional
      - intellij-idea-ultimate
      - webstorm
      - datagrip
      - clion
      - rubymine
      - goland
    state: present
    classic: yes
    channel: latest/edge
