---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: required
dist: bionic

branches:
  only:
    - master
    - molecule
    - dev

env:
  - ANSIBLE_VERSION=latest

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
      - python3-pip
      - docker.io

# before_install:

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint
  - pip install molecule
  - pip install docker

after_install:
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  # - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - yamllint *.yml && yamllint roles/
  - ansible-lint main.yml
  - ansible-playbook main.yml -i tests/inventory --syntax-check

  - cd roles/virtualbox && molecule test && cd ..
  - cd roles/new-user && molecule test && cd ..

script:
  # Basic role syntax check
  # - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  - ansible-playbook main.yml -i tests/inventory --tags "debian" --skip-tags "vpnauth"
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/

# after_success:
# after_failure:
# after_script:

# before_deploy:
# deploy:
# after_deploy:
