---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python3-pip

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint
  - pip install molecule

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  # - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  # - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  - yamllint *.yml && yamllint roles/
  - ansible-lint main.yml
  - ansible-playbook main.yml -i tests/inventory --syntax-check

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
