- hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/default/main.yml

  roles:
    - create-new-user
    - common
    - update
    - linux-headers
    - players
    - tools
    - vim
    - ides
    - browsers
    - keeweb
    - vpn
    - torrent
    - lang
    - kubernetes
    - comm
    # - sdkman # TODO: sdkman installation is not working yet
