- hosts: local
  # sudo: yes
  become: yes
  become_method: sudo
  roles:
    - create-new-user
    - common
    - update
    - linux-headers
    - players
    - tools
    - vim
    - ides
    - browsers
    - keeweb
#    - kubernetes
    - comm
    - sdkman # TODO: sdkman installation is not working yet
