---
- name: Start docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes
    use: auto

- name: Restart openssh
  become: true
  service:
    name: ssh
    state: started
    enabled: yes
    use: auto
