---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    username: nik

  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: check intellij
      stat:
        path: /home/{{ username }}/.IntelliJIdea2019.*
      register: idea_dir_status

    - name: check datagrip
      stat:
        path: /home/{{ username }}/.DataGrip2019.*
      register: datagrip_dir_status

    - name: check java
      stat:
        path: /home/{{ username }}/.java
      register: java_dir_status

    - name: Check sdkman jvms exist
      assert:
        that:
          - "not {{ item }}_dir_status.stat.exists"
      with_items:
        - idea
        - datagrip
        - java

    - name: check snap packages for idea
      snap:
        name: intellij-idea-ultimate
        state: present
        classic: yes
      check_mode: yes
      register: idea_status

    - name: check snap packages for datagrip
      snap:
        name: datagrip
        state: present
        classic: yes
      check_mode: yes
      register: datagrip_status

    - name: check snap packages for code
      snap:
        name: code
        state: present
        classic: yes
      check_mode: yes
      register: code_status

    - name: check snap packages for circleci
      snap:
        name: circleci
        state: present
        classic: yes
      check_mode: yes
      register: circleci_status

    - name: Check ide status
      assert:
        that: not {{ item }}_status.changed
      with_items:
        - idea
        - datagrip
        - code
        - circleci
