---
- name: Converge
  hosts: all
  vars:
    username: nik

  tasks:
    - name: "Update cache"
      apt:
        update_cache: yes

    - name: Add user
      user:
        name: "{{ username }}"

    - name: "Include create-new-user"
      include_role:
        name: "new-user"
