---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    username: nik

  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: Check if groups exists.
      user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        groups:
          - sudo
          - docker
          - "{{ username }}"
          - plugdev
          - lxd
          - libvirt
          - kvm
          - vboxusers
        append: yes
      check_mode: yes
      register: "groups_status"

    - name: Clone zsh
      stat:
        path: /home/{{ username }}/.oh-my-zsh
      register: zsh_status

    - name: install powerline fonts
      package:
        name: fonts-powerline
        state: present
      check_mode: yes
      register: "fonts_powerline_status"

    - name: Clone powerline fonts
      stat:
        path: /home/{{ username }}//.oh-my-zsh/custom/themes/powerlevel9k
      register: powerline_status

    - name: Copy default zshrc file
      stat:
        path: "/home/{{ username }}/.zshrc"
      register: zshrc_status

    - name: Clone bash-it
      stat:
        path: /home/{{ username }}/.bash-it
      register: bash_it_status

    - name: Clone tmux conf
      stat:
        path: /home/{{ username }}/.tmux.conf
      register: tmux_conf_status

    - name: Clone source.sh
      stat:
        path: /home/{{ username }}/.source.sh
      register: source_sh_status

    - name: copy script to disable ipv6
      stat:
        path: /home/{{ username }}/disable-ipv6.sh
      register: disable_ipv6_sh_status

    - name: Create ranger config directory if it does not exist
      stat:
        path: /home/{{ username }}/.config/ranger
      register: ranger_config_status

    - name: copy ranger rc.conf
      stat:
        path: /home/{{ username }}/.config/ranger/rifle.conf
      register: ranger_rc_conf_status

    - name: Assert checks
      assert:
        that:
          - not groups_status.changed
          - zsh_status.stat.exists
          - not fonts_powerline_status.changed
          - powerline_status.stat.exists
          - zshrc_status.stat.exists
          - bash_it_status.stat.exists
          - tmux_conf_status.stat.exists
          - source_sh_status.stat.exists
          - disable_ipv6_sh_status.stat.exists
          - ranger_config_status.stat.exists
          - ranger_rc_conf_status.stat.exists
