---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: install kernel headers and build tools
      apt:
        name:
          - build-essential
          - checkinstall
          - linux-generic
          - linux-headers-generic
        state: present
      check_mode: yes
      register: packages_status

    - name: Assert packages_status is installed
      assert:
        that:
          - not packages_status.changed
