---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: install media player and tools
      apt:
        name:
          - mplayer
          - vlc
          - ffmpeg
          - mpv
      state: present
      check_mode: yes
      register: packages_status

    - name: Assert packages are installed
      assert:
        that:
          - not packages_status.changed
