---
- name: Install docker
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker
    - docker.io
    - lxd
    - adb
    - snapd
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install kvm
  package:
    state: present
    name: "{{ item }}"
  with_items:
   - qemu-kvm 
   - libvirt-daemon-system 
   - libvirt-clients 
   - bridge-utils
   - virt-manager
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating a user named {{ username }} on the specified web server.
  user:
    name: "{{ username }}"
    # password: "{{ hashed_password }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
      - docker
      - "{{ username }}"
      # - microk8s
      - plugdev
      - lxd
      - docker
      - libvirt
      - kvm
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/{{ username }}/.ssh/id_rsa

# - name: Copy .ssh/id_rsa from host box to the remote box for user {{ username }}
#   become: true
#   copy:
#     src: ~/.ssh/id_rsa.pub
#     dest: /home/{{ username }}/.ssh/authorized_keys
#     mode: 0600
#     owner: "{{ username }}"
#     group: "{{ username }}"

- name: Add user to sudoers list
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ username }} ALL"
    line: "{{ username }} ALL=(ALL) ALL"
    state: present

- git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ username }}/.oh-my-zsh

- git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: /home/{{ username }}//.oh-my-zsh/custom/themes/powerlevel9k

- name: check if rules file exists
  stat:
    path: /home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template
  register: check_zsh_exists

#- name: Copy default zshrc file
#  copy: src="/home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template" dest="/home/{{ username }}/.zshrc"
#  when: check_zsh_exists.stat.exists == True

- git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /home/{{ username }}/.bash-it

- name: copy alias and export files
  synchronize:
    src: "{{ item }}"
    dest: /home/{{ username }}/.{{ item }}
  with_items:
    - alias.sh
    - tmux.conf
    - source.sh
    - zshrc
    - bashrc

- name: copy alias and export files
  synchronize:
    src: disable-ipv6.sh
    dest: /home/{{ username }}/disable-ipv6.sh

