---
- name: Install prereqs - docker, kvm, snapd
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker
    - docker.io
    - lxd
    - adb
    - snapd
    - vagrant
    - vagrant-libvirt
    - ruby-libvirt
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - zlib1g-dev
    - ruby-dev
    - bridge-utils
    - virt-manager
  tags:
    - debian

- name: Creating a user named {{ username }} on the specified machine with groups.
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
      - docker
      - "{{ username }}"
      - plugdev
      - lxd
      - docker
      - libvirt
      - kvm
    append: yes
  tags:
    - debian

# - name: Remove libvirt and qemu users
#   become: yes
#   user:
#     name: "Libvirt Qemu"
#     state: absent
#   tags:
#     - debian

# # - name: Add user to sudoers list
# #   lineinfile:
# #     dest: /etc/sudoers
# #     regexp: "{{ username }} ALL"
# #     line: "{{ username }} ALL=(ALL) ALL"
# #     state: present
# #   notify: Start docker
# #   notify: Start sshd

- name: Clone zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ username }}/.oh-my-zsh
  tags:
    - debian

- name: Clone powerline fonts
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: /home/{{ username }}//.oh-my-zsh/custom/themes/powerlevel9k
  tags:
    - debian

- name: check if zsh template file exists
  stat:
    path: /home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template
  register: check_zsh_exists
  tags:
    - debian

- name: Copy default zshrc file
  copy:
    src: "/home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "/home/{{ username }}/.zshrc"
  when: check_zsh_exists.stat.exists == True
  tags:
    - debian

- name: Clone bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /home/{{ username }}/.bash-it
  tags:
    - debian

- name: copy alias and export files
  synchronize:
    src: "{{ item }}"
    dest: /home/{{ username }}/.{{ item }}
  with_items:
    - alias.sh
    - tmux.conf
    - source.sh
  #     # - zshrc
  #     # - bashrc
  tags:
    - debian

- name: copy script to disable ipv6
  synchronize:
    src: disable-ipv6.sh
    dest: /home/{{ username }}/disable-ipv6.sh
  tags:
    - debian

- name: Install ranger
  package:
    name: ranger
    state: present
  tags:
    - debian

- name: Create ranger config directory if it does not exist
  file:
    path: /home/{{ username }}/.config/ranger
    state: directory
    mode: '0755'
  tags:
    - debian

- name: copy ranger rc.conf
  synchronize:
    src: rifle.conf
    dest: /home/{{ username }}/.config/ranger/rifle.conf
  tags:
    - debian
