---
- name: "Add cinnamon repo"
  apt_repository:
    repo: ppa:embrosyn/cinnamon
    state: present
    update_cache: yes
  tags:
    - debian

- name: Install prereqs - cinnamon, docker, kvm, snapd, libvirt
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - cinnamon
    - ranger
    - docker-compose
    - docker
    - docker.io
    - lxd
    - adb
    - snapd
    - ruby-libvirt
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - zlib1g-dev
    - ruby-dev
    - bridge-utils
    - virt-manager
  tags:
    - debian
    - server

- name: Creating a user named {{ username }} on the specified machine with groups.
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
      - docker
      - "{{ username }}"
      - plugdev
      - lxd
      - docker
      - libvirt
      - kvm
    append: yes
  tags:
    - debian
    - server

- name: Remove libvirt users
  become: yes
  user:
    name: "Libvirt"
    state: absent
  tags:
    - debian
    - server

- name: Remove qemu users
  become: yes
  user:
    name: "Qemu"
    state: absent
  tags:
    - debian
    - server

- name: Remove libvirt qemu users
  become: yes
  user:
    name: "Libvirt Qemu"
    state: absent
  tags:
    - debian
    - server

# - name: Add user to sudoers list
#   lineinfile:
#     dest: /etc/sudoers
#     regexp: "{{ username }} ALL"
#     line: "{{ username }} ALL=(ALL) ALL"
#     state: present
#   notify: Start docker
#   notify: Start sshd

- name: Clone zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ username }}/.oh-my-zsh
    version: master
  tags:
    - debian
    - server

- name: Clone powerline fonts
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: /home/{{ username }}//.oh-my-zsh/custom/themes/powerlevel9k
    version: master
  tags:
    - debian
    - server

- name: check if zsh template file exists
  stat:
    path: /home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template
  register: check_zsh_exists
  tags:
    - debian
    - server

- name: Copy default zshrc file
  copy:
    src: "/home/{{ username }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "/home/{{ username }}/.zshrc"
    remote_src: yes
  when: check_zsh_exists.stat.exists
  tags:
    - debian
    - server

- name: Clone bash-it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /home/{{ username }}/.bash-it
    version: master
  tags:
    - debian
    - server

- name: copy alias and export files
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.{{ item }}
  with_items:
    - alias.sh
    - tmux.conf
    - source.sh
  #     # - zshrc
  #     # - bashrc
  become: yes
  become_user: "{{ username }}"
  tags:
    - debian
    - server

- name: copy script to disable ipv6
  copy:
    src: disable-ipv6.sh
    dest: /home/{{ username }}/disable-ipv6.sh
  become: yes
  become_user: "{{ username }}"
  tags:
    - debian
    - server

- name: Install ranger
  package:
    name: ranger
    state: present
  tags:
    - debian
    - server

- name: Create ranger config directory if it does not exist
  file:
    path: /home/{{ username }}/.config/ranger
    state: directory
    mode: "0755"
  become: yes
  become_user: "{{ username }}"
  tags:
    - debian
    - server

- name: copy ranger rc.conf
  copy:
    src: rifle.conf
    dest: /home/{{ username }}/.config/ranger/rifle.conf
  become: yes
  become_user: "{{ username }}"
  tags:
    - debian
    - server
