---
- name: install kernel headers and build tools
  apt:
    name:
      - build-essential
      - checkinstall
      - linux-generic
      - linux-headers-generic
    state: present
  tags:
    - debian
    - server
