---
- name: install build-essential
  package:
    name: build-essential
    state: present
  tags:
    - debian

- name: install checkinstall
  apt:
    name: checkinstall
    state: present
  tags:
    - debian

- name: install linux-generic
  apt:
    name: linux-generic
    state: present
  tags:
    - debian

- name: install linux-headers-generic
  apt:
    name: linux-headers-generic
    state: present
  tags:
    - debian
