---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: check qbittorrent status
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - qbittorrent
        - qbittorrent-nox
      check_mode: yes
      register: qbittorrent_packages_status

    - name: check if /etc/sysctl.conf exists
      stat:
        path: /etc/sysctl.conf
      register: sysctl_conf_file_status

    - name: "Searching for net.ipv6.conf.default.disable_ipv6 = 1 in /etc/sysctl.conf"
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv6.conf.default.disable_ipv6 = 1"
        state: present
      check_mode: yes
      register: sysctl_conf_string_status
      # failed_when: presence is changed 

    - name: assert requirements for qbittorrent
      assert:
        that:
          - sysctl_conf_file_status.stat.exists
          - not sysctl_conf_string_status.changed
          - "not qbittorrent_packages_status.changed"
