---
- name: Converge
  hosts: all
  vars:
    username: nik

  tasks:
    - name: "Update cache"
      apt:
        update_cache: yes

    - name: add user
      user:
        name: "{{ username }}"

    - name: "Install linux-headers-generic"
      apt:
        name: ["gpg"]
        state: present

    - name: "Include virtualbox"
      include_role:
        name: "virtualbox"
