---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    username: nik

  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: Get all packages status
      apt:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - virtualbox-6.1
        - vagrant
        - docker-compose
        - docker
        - docker.io
        - lxd
        - virtinst
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - libvirt-dev
        - bridge-utils
        - virt-manager
      state: present
      check_mode: yes
      register: packages_status

    - name: vagrant plugin list
      shell: vagrant plugin list
      become: true
      become_user: "{{ username }}"
      args:
        executable: /bin/bash
        warn: yes
      register: vagrant_plugin_list

    - name: Remove /etc/docker/daemon.json
      stat:
        path: /etc/docker/daemon.json
      register: docker_json_status

    - name: Remove /usr/local/bin/minikube
      stat:
        path: /usr/local/bin/minikube
      register: minikube_status

    - name: snap status
      snap:
        name: ["helm", "microk8s"]
        state: present
        classic: yes
      register: snap_status

    - name: Assert installations
      assert:
        that:
          - not packages_status.changed
          - "vagrant_plugin_list.stdout is search('libvirt')"
          - "vagrant_plugin_list.stdout is search('mutate')"
          - not docker_json_status.stat.exists
          - minikube_status.stat.exists
          - not snap_status.changed
