---
- name: Update apt cache
  apt:
    update_cache: yes
  tags:
    - debian
    - server

- name: Update and upgrade apt
  apt:
    upgrade: "yes"
    update_cache: yes
  tags:
    - debian
    - server

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
  tags:
    - debian
    - server
