---
- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes
  # when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'elementary OS' or ansible_distribution == "Kali GNU/Linux"
  tags:
  - debian