- name: Install thunderbird
  apt:
    state: present
    name: thunderbird

- name: Does the Signal apt file exist?
  command: test -f {{ signal_apt_file }}
  register: signal_apt_exists
  ignore_errors: True

- name: Add signal apt file
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present
#  when: signal_apt_exists.rc == 1

- name: Add signal dev
  copy: content="deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" dest={{ signal_apt_file }} owner=root group=root mode=644
#  when: signal_apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes

- name: Run update and install signal
  apt:
    name: signal-desktop
    update_cache: yes