---
- name: Install thunderbird
  package:
    state: present
    name: thunderbird
  tags:
    - debian

# - name: Does the Signal apt file exist?
#   stat:
#     path: '{{ signal_apt_file }}'
#   register: signal_apt_exists

# - debug:
#     msg: signal status = {{ signal_apt_exists }}

# - name: Add signal apt file
#   apt_key:
#     url: https://updates.signal.org/desktop/apt/keys.asc
#     state: present
#   when: signal_apt_exists.stat.exists == False

# - name: Add signal dev
#   copy: content="deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" dest={{ signal_apt_file }} owner=root group=root mode=644
#   when: signal_apt_exists.stat.exists == False

# - name: Run update and install signal
#   apt:
#     name: signal-desktop-beta
#     update_cache: yes
