---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Example assertion
      assert:
        that: true

- name: Get pip tools status
  pip:
    name:
      - dtrx
      - speedtest-cli
    state: latest
  check_mode: yes
  register: pip_tools_status

- name: install tools
  apt:
    name:
      - htop
      - tree
      - ranger
      - tmux
      - calibre
      - openshot
      - kdenlive
      - audacity
      - texlive
      - blender
      - xclip
      - arandr
      - smartmontools
      - gsmartcontrol
      - bochs
      - adb
      - snapd
      - thunderbird
    state: latest
  check_mode: yes
  register: package_status

- name: Assert all packages are is installed
  assert:
    that:
      - not pip_tools_status.changed
      - not package_status.changed
