---
- name: Converge
  hosts: all
  tasks:
    - name: "Update cache"
      apt:
        update_cache: yes

    - name: "Add user"
      user:
        name: "{{ username }}"

    - name: "Include vim"
      include_role:
        name: "vim"

  vars:
    - username: nik
