---
- name: Install openvpn
  package:
    name: openvpn
    state: present
    update_cache: yes
  tags:
    - ubuntu

- name: Create /etc/openvpn
  file:
    path: /etc/openvpn
    state: directory
  tags:
    - ubuntu

# - name: Install nordvpn
#   apt:
#     deb: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb

- name: Download openvpn profiles
  get_url:
    url: https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
    dest: /etc/openvpn
  tags:
    - ubuntu

- name: openvpn easy-rsa
  file:
    state: directory
    path: /etc/openvpn/easy-rsa
  tags:
    - ubuntu

- name: Unzip openvpn profiles
  unarchive:
    src: /etc/openvpn/ovpn.zip
    dest: /etc/openvpn/
    remote_src: yes
    creates: "/etc/openvpn/ovpn_tcp"
  tags:
    - ubuntu
    - vpnauth
