---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    username: nik

  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: Install openvpn
      package:
        name: openvpn
        state: present
      check_mode: yes
      register: openvpn_status

    - name: stat /etc/openvpn
      stat:
        path: /etc/openvpn
      register: etc_openvpn_dir_stat

    - name: check asserts
      assert:
        that:
          - not openvpn_status.changed
          - etc_openvpn_dir_stat.stat.exists
