---
- name: install firefox
  package:
    name: firefox-esr
    state: present
  tags:
    - kali

- name: install firefox
  package:
    name: firefox
    state: present
  tags:
    - debian

- name: install chromium
  package:
    name: chromium-browser
    state: present
  tags:
    - debian

- name: install wget
  package:
    name: wget
    state: present
  tags:
    - debian

- name: install curl
  package:
    name: curl
    state: present
  tags:
    - debian

- name: Add chrome key if not present
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    state: present
  become: true
  tags:
    - debian

- name: Add Google Chrome repo
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb stable main
    update_cache: yes
    state: present
  tags:
    - debian

- name: Install Google Chrome
  apt:
    name: google-chrome-unstable
    state: present
  tags:
    - debian
