---
- name: install pip tools
  pip:
    name:
      - dtrx
      - speedtest-cli
    state: present
  tags:
    - debian
    - server

- name: install tools
  apt:
    name:
      - htop
      - tree
      - ranger
      - tmux
      - calibre
      - openshot
      - kdenlive
      - audacity
      - texlive
      - blender
      - xclip
      - arandr
      - smartmontools
      - gsmartcontrol
      - bochs
      - adb
      - snapd
      - thunderbird
    state: present
  tags:
    - debian
    - server
