- name: install openshot
  package:
    name: openshot
    state: present
  when: ansible_distribution != "Kali GNU/Linux"

- name: install kdenlive
  package:
    name: kdenlive
    state: present

- name: install audacity
  package:
    name: audacity
    state: present

- name: install texlive
  package:
    name: texlive
    state: present

- name: install ranger
  package:
    name: ranger
    state: present
    
- name: install texlive
  package:
    name: texlive
    state: present

- name: install xclip
  package:
    name: xclip
    state: present

- name: install calibre
  package:
    name: calibre
    state: present

- name: install tmux
  package:
    name: tmux
    state: present

- name: install smartmontools
  package:
    name: smartmontools
    state: present