- name: install openshot
  package:
    name: openshot
    state: present

- name: install kdenlive
  package:
    name: kdenlive
    state: present

- name: install audacity
  package:
    name: audacity
    state: present

- name: install texlive
  package:
    name: texlive
    state: present

- name: install ranger
  package:
    name: ranger
    state: present
    
- name: install texlive
  package:
    name: texlive
    state: present

- name: install xclip
  package:
    name: xclip
    state: present