---
- name: Install snap packages for golang
  snap:
    name: go
    state: present
    classic: yes
  tags:
    - debian

- name: Install ruby
  package:
    state: present
    name: ruby-full
  tags:
    - debian

- name: Install rust
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rustc
    - cargo
  tags:
    - debian

- name: Install node
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm
  tags:
    - debian

- name: Setup node modules prefix to user home
  shell: npm config set prefix "$HOME/.npm/node_modules"
  become: yes
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
  tags:
    - debian

- name: Setup npm cache to user home
  shell: npm config set cache "$HOME/.npm/npm_cache"
  become: yes
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
  tags:
    - debian

- name: Setup node modules tmp to user home
  shell: npm config set tmp "$HOME/.npm/tmp"
  become: yes
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
  tags:
    - debian

- name: check if sdkman template file exists
  stat:
    path: /home/{{ username }}/.sdkman/bin/sdkman-init.sh
  register: check_sdkman_exists
  tags:
    - debian

- name: Install sdkman
  shell: |
    curl -s "https://get.sdkman.io" | bash
  become: true
  become_user: "{{ username }}"
  when: check_sdkman_exists.stat.exists == False
  register: sdkman_result
  # args:
  #   warn: no
  tags:
    - debian

- name: check if sdkman template file exists
  stat:
    path: /home/{{ username }}/.sdkman/bin/sdkman-init.sh
  register: check_sdkman_before_lang_install
  tags:
    - debian

- name: Install sdk java
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install java
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk maven
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install maven
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk gradle
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install gradle
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk scala
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install scala
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk sbt
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install sbt
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk kotlin
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install kotlin
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian

- name: Install sdk springboot
  shell: |
    source /home/{{ username }}/.sdkman/bin/sdkman-init.sh && \
    sdk install springboot
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  register: command_result
  changed_when: "'is already installed' in command_result.stdout"
  ignore_errors: yes
  when: check_sdkman_before_lang_install.stat.exists == True
  tags:
    - debian