- name: Install snap packages for golang
  snap:
    name: go
    state: present
    classic: yes
  
- name: Install ruby
  package:
    state: present
    name: ruby-full
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'elementary OS'
# - name: Setup golib
#   command: mkdir /home/{{ username }}/golib

