- name: Install snap packages for lang
  snap:
    name: "{{ lang }}"
    state: present
    classic: yes
  with_items:
  - go
  - ruby-full

# - name: Setup golib
#   command: mkdir /home/{{ username }}/golib
  
    