---
# tasks file for virtualbox
- name: Add virtualbox key
  apt_key:
    id: 9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  tags:
    - debian
    - server

- name: Add ansible_distribution_release to deb location
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib
    state: present
  tags:
    - debian
    - server

- name: Add wolfgang vagrant key
  apt_key:
    url: https://vagrant-deb.linestarve.com/vagrant-deb.asc
    state: present
  tags:
    - debian
    - server

- name: Add vagrant unofficial repo
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com any main
    state: present
  tags:
    - debian
    - server

- name: Update cache
  apt:
    update_cache: yes
  tags:
    - debian
    - server

- name: Install prereqs docker, kvm, snapd, libvirt
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - vagrant
    - virtualbox-6.1
    - docker-compose
    - docker
    - docker.io
    - lxd
    - ruby-libvirt
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    # - libxslt-dev
    # - libxml2-dev
    - libvirt-dev
    # - zlib1g-dev
    # - ruby-dev
    - bridge-utils
    - virtinst
    - virt-manager
  tags:
    - debian
    - server

- name: vagrant plugin install vagrant-mutate
  shell: vagrant plugin install vagrant-mutate
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: true
  changed_when: false
  tags:
    - debian
    - server

- name: vagrant plugin install winrm
  shell: vagrant plugin install winrm
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  changed_when: false
  ignore_errors: true
  tags:
    - debian
    - server

- name: vagrant plugin install winrm-fs
  shell: vagrant plugin install winrm-fs
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  changed_when: false
  ignore_errors: true
  tags:
    - debian
    - server

- name: vagrant plugin install vagrant-libvirt
  shell: vagrant plugin install vagrant-libvirt
  become: true
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  changed_when: false
  tags:
    - debian
    - server
