---
# tasks file for virtualbox

- name: Remove old docker stuff
  package:
    name: docker-engine
    state: absent
  tags:
    - ubuntu

- name: Add virtualbox key
  apt_key:
    id: 9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  tags:
    - ubuntu

- name: Add ansible_distribution_release to deb location
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: present
  tags:
    - ubuntu

- name: Add wolfgang vagrant key
  apt_key:
    url: https://vagrant-deb.linestarve.com/vagrant-deb.asc
    state: present
  tags:
    - ubuntu

- name: Add vagrant unofficial repo
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com any main
    state: present
  tags:
    - ubuntu

- name: Install prereqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes
  tags:
    - ubuntu

- name: Install packages
  apt:
    state: fixed
    name:
      [
        "vagrant",
        "virtualbox-6.1",
        "docker-compose",
        "docker",
        "docker.io",
        "lxd",
      ]
  tags:
    - ubuntu

- name: Install packages
  apt:
    state: fixed
    name:
      [
        "ruby-libvirt",
        "qemu-kvm",
        "libvirt-daemon-system",
        "libvirt-clients",
        "libvirt-dev",
        "bridge-utils",
        "virtinst",
        "virt-manager",
      ]
  tags:
    - ubuntu

- name: Remove /etc/docker/daemon.json
  file:
    path: /etc/docker/daemon.json
    state: absent
  notify:
    - Start docker
  tags:
    - ubuntu

- name: vagrant plugin install vagrant-mutate
  command: vagrant plugin install vagrant-mutate
  become: true
  become_user: "{{ username }}"
  ignore_errors: true
  changed_when: false
  tags:
    - ubuntu

- name: vagrant plugin install winrm
  command: vagrant plugin install winrm
  become: true
  become_user: "{{ username }}"
  changed_when: false
  ignore_errors: true
  tags:
    - ubuntu

- name: vagrant plugin install winrm-fs
  command: vagrant plugin install winrm-fs
  become: true
  become_user: "{{ username }}"
  changed_when: false
  ignore_errors: true
  tags:
    - ubuntu

- name: vagrant plugin install vagrant-libvirt
  command: vagrant plugin install vagrant-libvirt
  become: true
  become_user: "{{ username }}"
  changed_when: false
  tags:
    - ubuntu

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    mode: 0755
    dest: /usr/local/bin/minikube
    validate_certs: no
  become: yes
  tags:
    - ubuntu

- name: Add kubectl key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - ubuntu

- name: Add kubectl apt_repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    path: /etc/apt/sources.list.d/kubernetes.list
    update_cache: yes
  tags:
    - ubuntu

- name: Install kubectl
  apt:
    name: kubectl
    state: present
  tags:
    - ubuntu

- name: Add helm apt key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    update_cache: yes
  tags:
    - ubuntu

- name: Add helm apt_repository
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: /etc/apt/sources.list.d/helm-stable-debian.list
    update_cache: yes
  tags:
    - ubuntu
- name: Install helm
  apt:
    name: helm
    state: present
  tags:
    - ubuntu
