---
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'elementary OS' or ansible_distribution == 'Kali GNU/Linux'

- name: Install htop
  package:
    name: htop
    state: present

- name: install wget
  package:
    name: wget
    state: present

- name: install curl
  package:
    name: curl
    state: present

- name: install ranger
  package:
    name: ranger
    state: present

- name: install tree
  package:
    name: tree
    state: present

- name: install powerline fonts
  package:
    name: fonts-powerline
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'elementary OS' or ansible_distribution == 'Kali GNU/Linux'
