---
- name: Install htop
  package:
    name: htop
    state: present
  tags:
    - debian
    - server

- name: install ranger
  package:
    name: ranger
    state: present
  tags:
    - debian
    - server

- name: install tree
  package:
    name: tree
    state: present
  tags:
    - debian
    - server

- name: install powerline fonts
  package:
    name: fonts-powerline
    state: present
  tags:
    - debian
    - server
