---
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Install htop
  apt:
    name: htop
    state: present
    update_cache: true

- name: install wget
  apt:
    name: wget
    state: present

- name: install curl
  apt:
    name: curl
    state: present

- name: install ranger
  apt:
    name: ranger
    state: present

- name: install tree
  apt:
    name: tree
    state: present
    