---
- name: install vim
  package:
    name: vim
    state: present
  tags:
    - debian

- name: Create vim directory
  file:
    path: /home/{{ username }}/.vim/autoload
    state: directory
  tags:
    - debian

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ username }}/.vim/autoload/plug.vim
  tags:
    - debian

- name: Place vimrc on ~/.vimrc
  copy:
    src: vimrc
    dest: /home/{{ username }}/.vimrc
    mode: "0644"
    owner: "{{ username }}"
  tags:
    - debian

- name: Install vim-plug
  command: vim +PluginInstall +qall
  become: yes
  become_user: "{{ username }}"
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: yes
  changed_when: false
  tags:
    - debian
