---
- name: Converge
  hosts: all
  vars:
    username: nik

  tasks:
    - name: update cache
      apt:
        name: snapd
        update_cache: yes

    - name: Add user
      user:
        name: "{{ username }}"

    - name: "Include kubernetes"
      include_role:
        name: "kubernetes"
